# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokemonTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'Then'
  pod 'Alamofire'
  pod 'SwiftEntryKit', '2.0.0'

end
